version: "3.8"

networks:
  customers_adm:
    name: customers_adm

services:
  nginx:
    image: nginx:latest
    container_name: customers_adm_nginx
    hostname: customers_adm_nginx
    restart: unless-stopped
    depends_on:
      - php
      - phpmyadmin
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - customers_adm

  php:
    image: php:8.2-fpm
    container_name: customers_adm_php
    hostname: customers_adm_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - customers_adm

  composer:
    image: composer:latest
    container_name: customers_adm_composer
    hostname: customers_adm_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - customers_adm

  mysql:
    image: "mysql/mysql-server:8.0"
    restart: unless-stopped
    container_name: customers_adm_mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - customers_adm

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: customers_adm_phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    networks:
      - customers_adm
